import {createRequire} from 'node:module';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),dependency=name=>require(process.env.TEST_MODULES?process.env.TEST_MODULES+'/'+name:name);
const {chromium}=dependency('playwright'),{PNG}=dependency('pngjs'),{PDFDocument}=dependency('pdf-lib');
const base=process.env.TEST_URL||'http://127.0.0.1:4173/';
await mkdir('test-results',{recursive:true});
const png=new PNG({width:600,height:400});png.data.fill(220);for(let i=3;i<png.data.length;i+=4)png.data[i]=255;
const image=Array.from(PNG.sync.write(png)),pdf=await PDFDocument.create();pdf.addPage([600,400]);const pdfBytes=Array.from(await pdf.save());
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write'],acceptDownloads:true});
const page=await context.newPage(),results=[],requests=[],errors=[];
page.on('request',r=>requests.push({method:r.method(),url:r.url(),body:r.postData()}));page.on('pageerror',e=>errors.push(e.message));
const pass=s=>{results.push(s);console.log('PASS '+s);};
const count=async n=>assert.equal(await page.locator('.page-item').count(),n);
const settle=async()=>{await page.locator('#loading').waitFor({state:'hidden'});};
const eventFiles=async(entries,type='drop',target='body',options={})=>page.evaluate(({entries,type,target,options})=>{
  const data=new DataTransfer();
  for(const entry of entries){const bytes=new Uint8Array(entry.bytes);const parts=entry.size?[bytes,new Uint8Array(entry.size-bytes.length)]:[bytes];data.items.add(new File(parts,entry.name,{type:entry.mime}));}
  if(options.delay){const file=data.files[0];const original=file.arrayBuffer.bind(file);Object.defineProperty(file,'arrayBuffer',{value:async()=>{await new Promise(resolve=>{window.finishIncoming=resolve;});return original();}});}
  const event=type==='paste'?new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}):new DragEvent(type,{dataTransfer:data,bubbles:true,cancelable:true});
  document.querySelector(target).dispatchEvent(event);return {prevented:event.defaultPrevented,dropEffect:data.dropEffect};
},{entries,type,target,options});
const file=(name,mime='image/png',bytes=image,size)=>({name,mime,bytes,size});
const nativeImagePaste=async()=>{
  await page.evaluate(async bytes=>{await navigator.clipboard.write([new ClipboardItem({'image/png':new Blob([new Uint8Array(bytes)],{type:'image/png'})})]);},image);
  await page.locator('.brand h1').click();await page.keyboard.press('Control+v');await settle();
};
const rectangle=async()=>{const b=await page.locator('#overlay').boundingBox();await page.mouse.move(b.x+b.width*.2,b.y+b.height*.2);await page.mouse.down();await page.mouse.move(b.x+b.width*.5,b.y+b.height*.5);await page.mouse.up();};
const clear=async()=>{await page.locator('#clear-all').click();await page.locator('#confirm-delete').click();await page.waitForFunction(()=>!document.querySelectorAll('.page-item').length&&!document.querySelector('#add-files').disabled);};
try {
  await page.goto(base);
  await nativeImagePaste();await count(1);await page.locator('#stage').waitFor({state:'visible'});
  const clipboardName=(await page.locator('.page-number').innerText()).replace(/^1\. /,'');
  const clipboardBytes=await page.evaluate(async()=>{const items=await navigator.clipboard.read();return Array.from(new Uint8Array(await (await items[0].getType('image/png')).arrayBuffer()));});
  pass('real clipboard image paste imports a local PNG');
  await nativeImagePaste();await count(1);assert.ok(await page.locator('#status').isHidden());
  assert.ok((await eventFiles([file(clipboardName,'image/png',clipboardBytes)])).prevented);await settle();await count(1);
  pass('repeated paste and same-name/content drop do not duplicate the clipboard image');
  await rectangle();const text='  自作テストの通常テキスト貼り付け\n位置指定コメント  ';
  await page.evaluate(text=>navigator.clipboard.writeText(text),text);await page.locator('#comment-text').focus();await page.keyboard.press('Control+v');
  assert.equal(await page.locator('#comment-text').inputValue(),text);await page.locator('#comment-text').press('Control+Enter');await count(1);
  pass('ordinary native text paste in the comment editor preserves text and creates no image');
  const beforeUrl=page.url();assert.ok((await eventFiles([file('drop-one.png'),file('drop-two.png'),file('drop.pdf','application/pdf',pdfBytes)])).prevented);
  await settle();await count(4);assert.equal(page.url(),beforeUrl);assert.ok(!await page.locator('body').evaluate(el=>el.classList.contains('file-dragging')));
  pass('multiple images and PDF drop use local import, prevent default navigation, and clear drag highlighting');
  await eventFiles([file('drop-one.png'),file('drop-two.png')]);await settle();await count(4);
  await eventFiles([file('invalid.svg','image/svg+xml')]);await settle();await count(4);assert.match(await page.locator('#status').innerText(),/対応する画像形式/);
  await eventFiles([file('bad-clipboard.png','image/png',[0,1,2])],'paste');await settle();await count(4);assert.match(await page.locator('#status').innerText(),/読み込めません/);
  pass('duplicate drop skips existing files; unsupported SVG and corrupt clipboard images show errors');
  await page.locator('.comment-open').click();await page.locator('#comment-text').fill('未保存の自作テストコメント');
  await eventFiles([file('draft-paste.png')],'paste');assert.ok(await page.locator('#unsaved-dialog').isVisible());await count(4);await page.locator('#draft-stay').click();
  assert.equal(await page.locator('#comment-text').inputValue(),'未保存の自作テストコメント');await count(4);
  await eventFiles([file('draft-drop.png')]);await page.locator('#draft-discard').click();await settle();await count(5);
  pass('image paste/drop respect the unsaved-comment dialog; stay preserves draft and discard then imports');
  const copied=await (async()=>{await page.locator('#copy-json').click();await page.locator('#copy-success-dialog').waitFor({state:'visible'});const json=JSON.parse(await page.evaluate(()=>navigator.clipboard.readText()));await page.locator('#close-copy-success').click();return json;})();
  assert.equal(copied.pages[0].comments[0].comment,text);assert.equal(copied.pages[0].file_name,clipboardName);assert.equal(copied.pages[3].original.unit,'pt');assert.ok(Math.abs(copied.pages[0].comments[0].region.x-.2)<.005);
  assert.ok(!JSON.stringify(copied).includes('base64'));assert.ok(!copied.instructions_for_ai.includes('UI screenshot'));
  const downloadPromise=page.waitForEvent('download');await page.locator('#download-json').click();const download=await downloadPromise;await download.saveAs('test-results/import-export.json');
  const saved=JSON.parse(await readFile('test-results/import-export.json','utf8'));delete saved.exported_at;delete copied.exported_at;assert.deepEqual(saved,copied);
  pass('clipboard and file JSON outputs agree after paste/drop, preserve comment/coordinates, and contain no image binary');
  await eventFiles([file('drag-preview.png')],'dragenter');await eventFiles([file('drag-preview.png')],'dragenter');assert.ok(await page.locator('body').evaluate(el=>el.classList.contains('file-dragging')));
  await page.screenshot({path:'test-results/import-drop-overlay.png'});await eventFiles([],'dragleave');assert.ok(await page.locator('body').evaluate(el=>el.classList.contains('file-dragging')));await eventFiles([],'dragleave');assert.ok(!await page.locator('body').evaluate(el=>el.classList.contains('file-dragging')));
  await eventFiles([file('drag-preview.png')],'dragenter');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.ok(!await page.locator('body').evaluate(el=>el.classList.contains('file-dragging')));
  const urlDrop=await page.evaluate(()=>{const data=new DataTransfer();data.setData('text/uri-list','https://example.invalid/private-image.png');const event=new DragEvent('drop',{dataTransfer:data,bubbles:true,cancelable:true});document.body.dispatchEvent(event);return event.defaultPrevented;});assert.ok(urlDrop);assert.equal(page.url(),beforeUrl);await count(5);
  pass('nested drag enter/leave and blur clear the overlay; URL drops cannot navigate or fetch external images');
  await eventFiles([file('slow.png')],'drop','body',{delay:true});await page.waitForFunction(()=>typeof window.finishIncoming==='function');
  await eventFiles([file('busy-paste.png')],'paste');assert.match(await page.locator('#status').innerText(),/処理中/);await count(5);
  await page.locator('#cancel-import').click();await page.evaluate(()=>window.finishIncoming());await settle();await count(5);
  pass('concurrent paste while loading is refused; cancelling a dropped file keeps prior work');
  await eventFiles([file('too-large.png','image/png',image,51*1024*1024)]);await settle();await count(5);assert.match(await page.locator('#status').innerText(),/50MB/);
  await eventFiles([file('empty.png','image/png',[])],'paste');await settle();await count(5);assert.match(await page.locator('#status').innerText(),/空のファイル/);
  pass('paste/drop share the per-file size limit and reject empty images');
  await clear();await eventFiles([file('large-a.png','image/png',image,49*1024*1024),file('large-b.png','image/png',image,49*1024*1024),file('large-c.png','image/png',image,49*1024*1024)]);await settle();await count(3);
  await eventFiles([file('total-limit.png','image/png',image,4*1024*1024)],'paste');await settle();await count(3);assert.match(await page.locator('#status').innerText(),/合計150MB/);
  pass('multi-file drop and image paste share the 150MB aggregate cap');
  await clear();await page.locator('#file-input').setInputFiles({name:'picker.png',mimeType:'image/png',buffer:Buffer.from(image)});await settle();await count(1);
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await page.locator('.import-hint').isVisible());await page.screenshot({path:'test-results/import-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'test-results/import-desktop.png',fullPage:true});
  pass('picker import still works; desktop/mobile hints and layout remain readable');
  const http=requests.filter(r=>/^https?:/.test(r.url));assert.ok(http.every(r=>r.method==='GET'&&!r.body&&new URL(r.url).origin===new URL(base).origin));assert.deepEqual(errors,[]);
  pass('all inputs perform no uploads or external requests and produce no runtime errors');
  await writeFile('test-results/import-inputs-report.json',JSON.stringify({checkedAt:new Date().toISOString(),base,results,errors,httpRequests:http.length,uploadedBodies:0},null,2));await writeFile('test-results/import-inputs-network.json',JSON.stringify(requests,null,2));
} finally {await context.close();await browser.close();}
