import {createRequire} from 'node:module';import {mkdir,writeFile,readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),dependency=n=>require(process.env.TEST_MODULES?process.env.TEST_MODULES+'/'+n:n);
const {chromium}=dependency('playwright'),{PNG}=dependency('pngjs'),{PDFDocument}=dependency('pdf-lib');
await mkdir('test-results',{recursive:true});const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write'],acceptDownloads:true});const page=await context.newPage(),requests=[],errors=[],results=[];
page.on('request',r=>requests.push({method:r.method(),url:r.url(),body:r.postData()}));page.on('pageerror',e=>errors.push(e.message));const pass=s=>{results.push(s);console.log('PASS '+s);};
function finiteWebm(bytes,durationMs=3000){const data=Buffer.from(bytes),id=Buffer.from([0x15,0x49,0xa9,0x66]);let at=0;while((at=data.indexOf(id,at))>=0){if(data[at-3]!==0x53||data[at-2]!==0xab||data[at-1]!==0x84)break;at+=4;}assert.ok(at>=0);const duration=data.indexOf(Buffer.from([0x44,0x89]),at+4);assert.ok(duration>=0&&duration<at+80);const size=data[duration+2];if(size===0x84)data.writeFloatBE(durationMs,duration+3);else if(size===0x88)data.writeDoubleBE(durationMs,duration+3);else throw Error('Unexpected WebM duration encoding');return data;}
const count=async n=>assert.equal(await page.locator('.page-item').count(),n);const load=async files=>{await page.locator('#file-input').setInputFiles(files);await page.locator('#loading').waitFor({state:'hidden'});};
const seek=async time=>{await page.locator('#video-seek').evaluate((el,time)=>{el.value=time;el.dispatchEvent(new Event('input',{bubbles:true}));},time);await page.waitForFunction(time=>!document.querySelector('#video').seeking&&Math.abs(document.querySelector('#video').currentTime-time)<.025,time);};
const rect=async(a={x:.2,y:.25},z={x:.6,y:.65})=>{const b=await page.locator('#overlay').boundingBox();await page.mouse.move(b.x+b.width*a.x,b.y+b.height*a.y);await page.mouse.down();await page.mouse.move(b.x+b.width*z.x,b.y+b.height*z.y);await page.mouse.up();};
const copy=async()=>{await page.locator('#copy-json').click();await page.locator('#copy-success-dialog').waitFor({state:'visible'});const output=JSON.parse(await page.evaluate(()=>navigator.clipboard.readText()));await page.locator('#close-copy-success').click();return output;};
try {
  await page.goto('http://127.0.0.1:4173/');
  const recording=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d'),stream=canvas.captureStream(30),recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8'}),chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);let frame=0;const draw=()=>{ctx.fillStyle=frame++<45?'#ef4545':'#3874dc';ctx.fillRect(0,0,640,360);ctx.fillStyle='#fff';ctx.fillRect(100+frame,100,140,100);};draw();const interval=setInterval(draw,33);const done=new Promise(resolve=>recorder.onstop=resolve);recorder.start();await new Promise(resolve=>setTimeout(resolve,3000));recorder.stop();await done;clearInterval(interval);stream.getTracks().forEach(t=>t.stop());return Array.from(new Uint8Array(await new Blob(chunks).arrayBuffer()));});
  const video=finiteWebm(recording);await writeFile('test-results/self-made.webm',video);
  await page.evaluate(()=>{window.videoUrls=[];window.revoked=[];const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=blob=>{const url=create(blob);if(blob.type.startsWith('video/'))window.videoUrls.push(url);return url;};URL.revokeObjectURL=url=>{window.revoked.push(url);revoke(url);};});
  await load({name:'self-made.webm',mimeType:'video/webm',buffer:video});await count(1);await page.locator('#stage').waitFor({state:'visible'});assert.ok(await page.locator('#video-controls').isVisible());assert.equal(await page.locator('#video').evaluate(v=>v.videoWidth),640);assert.equal(await page.locator('#video').evaluate(v=>v.videoHeight),360);assert.ok(await page.locator('#video').evaluate(v=>v.paused));pass('finite local WebM loads paused with native dimensions and duration');
  const activeUrl=await page.locator('#video').getAttribute('src');await page.locator('#video-toggle').click();await page.waitForFunction(()=>document.querySelector('#video').currentTime>.25);assert.ok(!await page.locator('#video').evaluate(v=>v.paused));await rect();assert.ok(await page.locator('#video').evaluate(v=>v.paused));const frozen=await page.locator('#video').evaluate(v=>v.currentTime);await page.locator('#comment-text').fill('Self-made comment while playing');await page.locator('#comment-text').press('Control+Enter');const first=await copy();assert.ok(Math.abs(first.pages[0].comments[0].time_seconds-frozen)<.001);pass('playback advances; region gesture pauses and saves its fixed currentTime');
  await seek(0);await seek(3);await seek(1.25);await rect();await page.locator('#comment-text').fill('  Self-made timestamp comment\n');await page.locator('#editor button[type=submit]').click();let output=await copy();assert.equal(output.files[0].type,'video');assert.equal(output.files[0].mime_type,'video/webm');assert.equal(output.pages[0].media_type,'video');assert.equal(output.time_system.units,'seconds');assert.equal(output.pages[0].comments[1].time_seconds,1.25);for(const [key,value] of Object.entries({x:.2,y:.25,width:.4,height:.4}))assert.ok(Math.abs(output.pages[0].comments[1].region[key]-value)<.005);assert.equal(output.pages[0].comments[1].comment,'  Self-made timestamp comment\n');assert.ok(!JSON.stringify(output).includes('blob:'));pass('seek, raw comment, full-frame normalized region and video metadata export accurately');
  await seek(2.25);assert.equal(await page.locator('#overlay .region').count(),0);await page.locator('.comment-open').nth(1).click();await page.waitForFunction(()=>!document.querySelector('#video').seeking);assert.ok(Math.abs(await page.locator('#video').evaluate(v=>v.currentTime)-1.25)<.025);assert.match(await page.locator('#editor-title').innerText(),/00:01.250/);await page.locator('#comment-text').fill('draft before seek');await page.locator('#video-toggle').click();assert.ok(await page.locator('#unsaved-dialog').isVisible());await page.locator('#draft-stay').click();assert.equal(await page.locator('#comment-text').inputValue(),'draft before seek');await page.locator('#video-seek').evaluate(el=>{el.value=2.25;el.dispatchEvent(new Event('input',{bubbles:true}));});assert.ok(await page.locator('#unsaved-dialog').isVisible());await page.locator('#draft-stay').click();assert.ok(Math.abs(await page.locator('#video').evaluate(v=>v.currentTime)-1.25)<.025);await page.locator('#cancel-edit').click();await page.locator('#draft-discard').click();pass('other-time regions hide; comment selection seeks to its timestamp; unsaved play request can be cancelled');
  for(let i=0;i<4;i++)await page.locator('#zoom-in').click();await rect({x:.03,y:.03},{x:.1,y:.15});await page.locator('#comment-text').fill('Self-made zoomed video comment');await page.locator('#editor button[type=submit]').click();output=await copy();assert.equal(output.pages[0].comments[2].time_seconds,1.25);assert.ok(Math.abs(output.pages[0].comments[2].region.x-.03)<.005);await page.locator('#fit').click();pass('zoom leaves video time and normalized coordinates independent of viewport');
  const downloadPromise=page.waitForEvent('download');await page.locator('#download-json').click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/^ココヲコウ-\d{4}-\d{2}-\d{2}\.json$/);await download.saveAs('test-results/video-export.json');assert.deepEqual(JSON.parse(await readFile('test-results/video-export.json','utf8')),output);assert.ok(!Object.hasOwn(output,'schema_version'));assert.ok(!Object.hasOwn(output,'exported_at'));pass('clipboard and file outputs agree, omit removed fields, and preserve filename');
  const png=new PNG({width:100,height:100});png.data.fill(255);const pdf=await PDFDocument.create();pdf.addPage([100,100]);await load([{name:'self.png',mimeType:'image/png',buffer:PNG.sync.write(png)},{name:'self.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())}]);await count(3);await page.locator('#video-toggle').click();await page.locator('.page-item').nth(1).click();await page.locator('#stage').waitFor({state:'visible'});assert.ok(await page.locator('#video-controls').isHidden());assert.ok(await page.locator('#video').evaluate(v=>v.paused&&!v.getAttribute('src')));await page.locator('.page-item').nth(2).click();await page.locator('#stage').waitFor({state:'visible'});assert.equal(await page.locator('#canvas').evaluate(c=>c.width>0),true);await page.locator('.page-item').first().click();await page.locator('#stage').waitFor({state:'visible'});assert.ok(await page.locator('#video').evaluate(v=>v.paused&&v.currentTime===0));pass('mixed image/PDF/video navigation stops and detaches playback; returning to video resets it');
  const mp4=Buffer.from(await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const ctx=canvas.getContext('2d'),stream=canvas.captureStream(30),recorder=new MediaRecorder(stream,{mimeType:'video/mp4;codecs=avc1.42001E'}),chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);let i=0;const timer=setInterval(()=>{ctx.fillStyle=i++%2?'#27684f':'#cfd9ec';ctx.fillRect(0,0,640,360);},33);const done=new Promise(resolve=>recorder.onstop=resolve);recorder.start();await new Promise(resolve=>setTimeout(resolve,1000));recorder.stop();await done;clearInterval(timer);stream.getTracks().forEach(t=>t.stop());return Array.from(new Uint8Array(await new Blob(chunks).arrayBuffer()));}));await writeFile('test-results/self-made.mp4',mp4);await load({name:'self-made.mp4',mimeType:'video/mp4',buffer:mp4});await count(4);await page.locator('.page-item').nth(3).click();await page.locator('#stage').waitFor({state:'visible'});await seek(.2);await rect();await page.locator('#comment-text').fill('Self-made MP4 comment');await page.locator('#editor button[type=submit]').click();const mp4Export=await copy();assert.equal(mp4Export.files[3].mime_type,'video/mp4');assert.equal(mp4Export.pages[3].comments[0].time_seconds,.2);await writeFile('test-results/video-mp4-export.json',JSON.stringify(mp4Export,null,2));await page.locator('.page-remove').nth(3).click();await page.locator('#confirm-delete').click();await page.waitForFunction(()=>!document.querySelector('#add-files').disabled);await count(3);await page.locator('.page-item').first().click();await page.locator('#stage').waitFor({state:'visible'});pass('self-made H.264 MP4 decodes, seeks and exports timestamp/region metadata');
  await load({name:'self-made.webm',mimeType:'video/webm',buffer:video});await count(4);await page.locator('.page-remove').last().click();await page.locator('#confirm-delete').click();await page.waitForFunction(()=>!document.querySelector('#add-files').disabled);await count(3);await load({name:'unsupported.mov',mimeType:'video/quicktime',buffer:video});await count(3);assert.match(await page.locator('#status').innerText(),/形式/);await load({name:'broken.mp4',mimeType:'video/mp4',buffer:Buffer.from('broken')});await count(3);assert.ok(await page.locator('#status').isVisible());await load({name:'empty.webm',mimeType:'video/webm',buffer:Buffer.alloc(0)});await count(3);assert.match(await page.locator('#status').innerText(),/空/);await writeFile('test-results/large-video.webm',Buffer.alloc(51*1024*1024));await load('test-results/large-video.webm');await count(3);assert.match(await page.locator('#status').innerText(),/形式・コーデック/);pass('identical video re-add works; unsupported, corrupt/empty and large corrupt videos preserve prior data');
  await load({name:'over-duration.webm',mimeType:'video/webm',buffer:finiteWebm(recording,21601000)});await count(4);assert.ok(await page.locator('#status').isHidden());await page.locator('.page-item').last().click();await page.locator('#stage').waitFor({state:'visible'});assert.ok(await page.locator('#video').evaluate(v=>v.duration>21600));assert.match(await page.locator('#video-time').innerText(),/06:00:01/);await page.locator('.page-remove').last().click();await page.locator('#confirm-delete').click();await page.waitForFunction(()=>!document.querySelector('#add-files').disabled);await page.locator('.page-item').first().click();await page.locator('#stage').waitFor({state:'visible'});await count(3);pass('over-six-hour declared duration metadata loads and displays without the old cap');
  const pendingBefore=await page.evaluate(()=>window.videoUrls.length);await page.evaluate(()=>{window.originalMediaSrc=Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype,'src');Object.defineProperty(HTMLMediaElement.prototype,'src',{...window.originalMediaSrc,set(value){if(this.tagName==='VIDEO'&&!this.id&&value.startsWith('blob:'))this.heldTestUrl=value;else window.originalMediaSrc.set.call(this,value);}});});await page.locator('#file-input').setInputFiles({name:'cancel-video.webm',mimeType:'video/webm',buffer:video});await page.waitForFunction(n=>window.videoUrls.length>n,pendingBefore);await page.locator('#cancel-import').click();await page.locator('#loading').waitFor({state:'hidden'});await page.evaluate(()=>Object.defineProperty(HTMLMediaElement.prototype,'src',window.originalMediaSrc));await count(3);assert.ok(await page.evaluate(()=>window.revoked.includes(window.videoUrls.at(-1))));pass('cancel during metadata loading releases its blob and retains existing video/image/PDF');
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-results/video-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await seek(1.25);await page.screenshot({path:'test-results/video-desktop.png',fullPage:true});
  await page.locator('.page-remove').first().click();await page.locator('#confirm-delete').click();await page.waitForFunction(()=>!document.querySelector('#add-files').disabled);await count(2);assert.ok(await page.evaluate(url=>window.revoked.includes(url),activeUrl));assert.ok(await page.locator('#video').evaluate(v=>v.paused&&!v.getAttribute('src')));output=await copy();assert.ok(!output.files.some(f=>f.type==='video'));assert.ok(!Object.hasOwn(output,'time_system'));await load({name:'self-made.webm',mimeType:'video/webm',buffer:video});await count(3);pass('mobile layout is bounded; deleting video releases blob/decoder, removes metadata, and permits re-add');
  await page.locator('#clear-all').click();await page.locator('#confirm-delete').click();await page.waitForFunction(()=>!document.querySelector('#add-files').disabled);await count(0);assert.ok(await page.evaluate(()=>window.videoUrls.every(url=>window.revoked.includes(url))));assert.ok(await page.locator('#video').evaluate(v=>v.paused&&!v.getAttribute('src')));pass('clear-all releases every successful and failed video blob and decoder');
  const http=requests.filter(r=>/^https?:/.test(r.url));assert.ok(http.every(r=>r.method==='GET'&&!r.body&&new URL(r.url).origin==='http://127.0.0.1:4173'));assert.deepEqual(errors,[]);pass('native video processing sends no files/comments or external requests and has no runtime errors');await writeFile('test-results/video-report.json',JSON.stringify({results,errors,httpRequests:http.length,uploadedBodies:0},null,2));await writeFile('test-results/video-network.json',JSON.stringify(requests,null,2));
}finally{await context.close();await browser.close();}
